# Use this example code to connect the project with your database
# You will need to create a file named <database.yml> with this code (or modify the name of this file)
# also you will need to add or edit the values in <.env.exameple>

default: &default
  adapter: postgresql
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PW'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT'] %>
test:
  <<: *default
  database: <%= ENV['DATABASE_TEST'] %>
production:
  database: <%= ENV['DATABASE_URL'] %>
  